### ISSUE TITLE
Front-end is missing

### ISSUE THREAD

**Issue by DeepeshKalura** [Ysrishti-04/smsspamdetection#1]
Make a front-end with gradio to show case what your model do

folder structure : -

app
 __init__.py
 all your model implementation

main.py <-- gradio code
test

**Comment by Ysrishti-04** [comment]
> Make a front-end with gradio to show case what your model do
> 
> folder structure : -
> 
> app **init**.py all your model implementation
> 
> main.py <-- gradio code test

![front-end](https://github.com/Ysrishti-04/smsspamdetection/assets/150606347/367d2baf-dab3-4182-8c4c-bb71cb5ac293)
I have tried to make a front-end using Gradio library

**Comment by DeepeshKalura** [comment]
Hmm for good enough, now for noob like me write a way to run that program
in Readme valla I will closed that issue with success.

**Comment by DeepeshKalura** [comment]
What I want is a readme file in which you will explain 
1. what is project all about and 
2. step to way run locally
3. How others person can contribute on your project.

**Comment by Ysrishti-04** [comment]
okay!
By tomorrow I will write the readme file

**Comment by DeepeshKalura** [comment]
I am closing this issue because it solve all the problem front-end issue in this project
